### ISSUE TITLE
Minimize Options on Top Bar

### ISSUE THREAD

**Issue by shli3** [UWindsorCSS/hub#112]
I think if we merge the "About" with the "Home" (place the "About" at the bottom of homepage), and get rid of that "Contribute" option on the top bar since there's already a button on the guide, the top bar will look nicer.

Right now, I think there's way too much going on there. The "About" Page seems super static and could easily just be put at the bottom of the homepage.

**Comment by EricPickup** [comment]
Thanks for the idea.
Home page is meant for news and will continue to expand, so we shouldn't move about info to that. About is arguably the most important page/content so people can learn what CSS is and elections. Contribute button is meant for contribution to the entire app which is much more complex than contributing to the markdown guide which is why they're separate buttons and the markdown button only appears on that one page.
